补充和修正部分模组的翻译及增加 KubeJS 的 startup.js 翻译
HaloSense/create_astral_translation_zhcn pull request #7
Opened 2023-02-02 13:14 UTC by spaceskynet

感觉 Ad Astra 的翻译和指南书还得好好确认一下，为了防止冲突，我就暂时不加了（如果你要加上可以直接去模组的官方仓库里找）。

像 custommachinery、farmersdelight、techreborn这些模组翻译有些缺漏或者错误，还有 minecraft 里面翻译我感觉是不是多了一些异常字符，我把它删除了，你可以好好确认一下。

还有那些还没有官方译名的模组，我建议itemGroup名称先暂时英文原文比较好，如果有人去搜索还没有的中文名称，可能无法正确定位模组。

2023-02-02 13:37 UTC, lrcno6 commented
minecraft的en_us多的不是异常字符，是回复的饱食度等数据

2023-02-02 13:40 UTC, spaceskynet commented
> minecraft的en_us多的不是异常字符，是回复的饱食度等数据

我运行游戏时显示不出来，就显示了名称后面跟着“乱码”

2023-02-02 13:41 UTC, lrcno6 commented
关闭强制unicode

2023-02-02 13:42 UTC, spaceskynet commented
> 关闭强制unicode

话说这个有必要吗，不是默认加了苹果皮mod吗？

2023-02-02 13:47 UTC, lrcno6 commented
我也好奇有无必要，但是它不是乱码

2023-02-02 20:43 UTC, HaloSense commented
我倾向于保留，一方面是尽量少的进行改动，保持原汁原味，另一方面我觉得这个也挺好玩的

2023-02-02 21:15 UTC, HaloSense requested changes
进行了一些简单校对

2023-02-02 21:15 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/catwalksinc/lang/zh_cn.json
> +  "misc.catwalksinc.catwalk.usage": "放置后，它会改变形状以匹配周围环境。\n栈桥与其他栈桥、大多数门、梯子和其他一些方块相连。 如果那个方块在上面一个方块，而栈桥正上方的空间是空的，它就会变成楼梯。\n此外，栈桥在一些可交互方块（如漏斗和箱子）前不会有栏杆。\n可以使用活动扳手覆盖此默认连接设置。\n对于楼梯，正常点击会在启用和关闭栏杆之间循环，而按住 Sh
“那个方块在上面一个方块”？我没看太懂。建议重新确认这几句的语义，润色一下

2023-02-02 21:15 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/doodads/lang/zh_cn.json
> +    "block.doodads.asphalt": "沥青",
```suggestion
    "block.doodads.asphalt": "安山岩路面",
```
整合包把沥青改为了安山岩路面（Andesite Pavement）。

2023-02-02 21:15 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/farmersdelight/lang/zh_cn.json
> +  "item.farmersdelight.vegetable_noodles": "蔬菜拉面",
```suggestion
  "item.farmersdelight.vegetable_noodles": "歪比巴卜面",
```
整合包将蔬菜拉面改为了Guljalabala，没查到什么特殊释义，翻译为“歪比巴卜面”。

2023-02-02 21:15 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/libraryferret/lang/zh_cn.json
> +  "gui.libraryferret.props.description.boolean.creative.enable_item_group_ferret": "在创造菜单中启用或禁用\"Ferret item\"组。 要完全禁用项目/块，请使用自定义数据包或使用 mod KubeJS/Crafttweaker。",
这块咋回事？项目/块？机翻？物品/方块才对吧？

2023-02-02 21:15 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/minecraft/lang/zh_cn.json
> +  "item.minecraft.apple": "苹果",
如果去掉饱食度图标的话其实这些名称没变的条目可以删除，简洁一些。

2023-02-02 21:15 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/minecraft/lang/zh_cn.json
> +  "item.minecraft.potato": "土豆",
这里是不是我写错了，马铃薯

2023-02-03 05:20 UTC, spaceskynet commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
我查了下词典，改成“烧制”可能比较好，还有这里的16个物品原本就是16 items

2023-02-03 05:41 UTC, spaceskynet commented on v2.0/resourcepacks/create_astral_translation/assets/minecraft/lang/zh_cn.json
> +  "item.minecraft.apple": "苹果",
我不能完全确定哪些是整合包里名称没变的条目，这部分如果要删除就麻烦你弄一下了

2023-02-03 05:46 UTC, HaloSense commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
> 我查了下词典，改成“烧制”可能比较好，还有这里的16个物品原本就是16 items

我的意思是问你，这里是原版熔炉的熔炼，还是匠魂熔化炉的熔融；以及我并不清楚同种燃料在匠魂熔化炉中的热值和其在熔炉中的热值有什么联系。考虑到熔化炉那个UI，我觉得没办法定量确定关系、

2023-02-03 05:50 UTC, spaceskynet commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
这里如果真要深究那就得进游戏里实践操作了，不过我想翻译过程中这种情况应该会出现很多次，我的建议是先根据英文的原文来，像这种可能需要实践操作验证的可以先记录下来，后面统一进行实践操作验证后更改

2023-02-03 06:01 UTC, lrcno6 commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
应该是熔炉吧
匠魂炉子的话应该是时间，且不同物品熔炼时间不同
个人觉得译作熔炼合适，因为原版熔炉的操作也译作熔炼，以及Create的bulk smelting也译作批量熔炼

2023-02-03 06:02 UTC, HaloSense commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
> 应该是熔炉吧 匠魂炉子的话应该是时间，且不同物品熔炼时间不同 个人觉得译作熔炼合适，因为原版熔炉的操作也译作熔炼，以及Create的bulk smelting也译作批量熔炼

同意

2023-02-03 06:20 UTC, spaceskynet commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
那就改成 _熔炼_ 吧，然后是关于 _16个物品_ ，我进游戏试了试，发现只能烧5个物品，而且我看了下生物质颗粒所属模组官方的仓库里，最新的中文翻译里改成了5个物品（最新的英文原文直接删掉了能烧几个物品的描述，旧版的中文翻译和其他语言的翻译曾经写的是6个），不清楚整合包官方是不是写错了还是其他什么情况

2023-02-03 07:01 UTC, lrcno6 commented
话说，有些模组汉化，难道不能投i18n吗

2023-02-03 07:27 UTC, HaloSense commented on v2.0/kubejs/startup_scripts/startup.js
> +      text.add(2, [Text.of('（它实际上能熔融 ').darkGreen(), Text.of('16个物品').green(), Text.of("，请忽略上面说的）").darkGreen()]);
关于这一点还是问一下开发组吧，万一是bug啥的

2023-02-03 11:33 UTC, spaceskynet reviewed
wait for next step

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/catwalksinc/lang/zh_cn.json
> +  "misc.catwalksinc.paint_roller.usage": "在工艺网格中结合 1-4 种染料来填充或重新填充。 一种染料等于八点耐久度。\n可绘制的方块是从配方中自动推断出来的。 如果一个方块的配方中有一种染料被方块包围并且最终产生八个方块，那么该方块将是可染色的。 使用涂刷滚筒，您可以为世界中的任何此类方块染色，每次染色会消耗涂刷滚筒的 1 点耐久度。\n可以通过右键单
工艺网格？原文是不是crafting grid？

以及别的地方也有这个问题：中文的标点符号都是全角的，不需要在句号后加空格。耐久度建议改为耐久值

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "deprecated.block.createaddition.electric_motor.tooltip.summary": "从 _FE_ 产生_应力_并且可调节_速度_。能量消耗基于设置的 _RPM_。",
```suggestion
  "deprecated.block.createaddition.electric_motor.tooltip.summary": "从 _FE_ 产生_应力_并且可调节_速度_。能量消耗量和设置的 _RPM_有关。",
```
我不知道这两侧各一个下划线是干啥的

基于RPM怎么读怎么怪

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "block.createaddition.accumulator.tooltip.behaviour2": "接受除顶部以及已连接到未标记的_连接器_的任何_线缆_之外的任何一侧的 _FE_。",
这么多“的”看得我头晕

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "block.createaddition.connector_gold.tooltip.action1": "当拿着_金线轴_右击两个_连接器_来建立一个_线缆连接_。",
```suggestion
  "block.createaddition.connector_gold.tooltip.action1": "手持_金线轴_右击两个_连接器_来建立一个_线缆连接_。",
```

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "block.createaddition.redstone_relay.tooltip.behaviour1": "提供 _FE_ 给左右连接至标记为_白色_的_连接器_的_线缆_。",
这句话没看懂

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "block.createaddition.redstone_relay.tooltip.behaviour2": "接受除顶部以外的任何一侧的 _FE_ 和连接到未标记的_连接器_上的任何_线缆_的 _FE_。",
这句话也是

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "block.createaddition.furnace_burner.tooltip.summary": "这个_熔炉_不会熔炼物品，但可以用来为_熔炉引擎_提供动力，且不需要熔炼配方。可以使用_漏斗_来输入_燃料_。",
这一句和下面好几句的熔炉都应该是燃烧炉吧

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "createaddition.ponder.liquid_blaze_burner.text_2": "将允许它通过桶接受液体燃料",
```suggestion
  "createaddition.ponder.liquid_blaze_burner.text_2": "让它可以接受用桶倒入的液体燃料",
```

2023-02-03 13:59 UTC, HaloSense commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "createaddition.ponder.liquid_blaze_burner.text_3": "- 或通过管道。",
```suggestion
  "createaddition.ponder.liquid_blaze_burner.text_3": "——或者用管道输入。",
```

2023-02-03 17:02 UTC, HaloSense commented
名字中的饱食度图标可以去了，Lasky说是老版本遗留下来的东西

2023-02-03 18:08 UTC, HaloSense commented
Lasky在astral的最新commit把所有改过名字的物品方块都提出来了，剩下没改过的都去掉了，详见discord
赞美他

2023-02-04 03:31 UTC, spaceskynet commented on v2.0/resourcepacks/create_astral_translation/assets/createaddition/lang/zh_cn.json
> +  "deprecated.block.createaddition.electric_motor.tooltip.summary": "从 _FE_ 产生_应力_并且可调节_速度_。能量消耗基于设置的 _RPM_。",
你进游戏看看就知道了，下划线是**加粗**，不像markdown是 _斜体_

2023-02-04 03:35 UTC, spaceskynet commented on v2.0/resourcepacks/create_astral_translation/assets/catwalksinc/lang/zh_cn.json
> +  "misc.catwalksinc.paint_roller.usage": "在工艺网格中结合 1-4 种染料来填充或重新填充。 一种染料等于八点耐久度。\n可绘制的方块是从配方中自动推断出来的。 如果一个方块的配方中有一种染料被方块包围并且最终产生八个方块，那么该方块将是可染色的。 使用涂刷滚筒，您可以为世界中的任何此类方块染色，每次染色会消耗涂刷滚筒的 1 点耐久度。\n可以通过右键单
耐久度我觉得更合适些，我也看了看[百科](https://wiki.biligame.com/mc/%E7%89%A9%E5%93%81%E8%80%90%E4%B9%85)，写的也是耐久度

2023-02-04 07:11 UTC, HaloSense commented
我觉得没啥问题了，合并了

2023-02-04 07:11 UTC, merged